### ISSUE TITLE
Microsoft.Data.Sqlite.SqliteException

### ISSUE THREAD

**Issue by danixbsc** [albx/WebTodoList#4]
Quando effettuo una richiesta GET: https://localhost:44387/api/Todo, viene sollevata la seguente eccezione:

> Microsoft.Data.Sqlite.SqliteException
>   HResult=0x80004005
>   Messaggio=SQLite Error 1: 'no such table: TodoItems'.
>   Origine=Microsoft.Data.Sqlite
>   Analisi dello stack:
>    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
>    at Microsoft.Data.Sqlite.SqliteCommand.<PrepareAndEnumerateStatements>d__64.MoveNext()
>    at Microsoft.Data.Sqlite.SqliteCommand.<GetStatements>d__54.MoveNext()
>    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
>    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
>    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
>    at System.Data.Common.DbCommand.ExecuteReader()
>    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
>    at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
>    at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
>    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
>    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
>    at WebTodoList.Api.Services.TodoControllerServices.GetTodoListItems(Boolean hideIfDone) in C:\Users\Daniele\Source\Repos\albx\WebTodoList\src\WebTodoList.Api\Services\TodoControllerServices.cs:line 29
>    at WebTodoList.Api.Controllers.TodoController.Get(Boolean hideIfDone) in C:\Users\Daniele\Source\Repos\albx\WebTodoList\src\WebTodoList.Api\Controllers\TodoController.cs:line 23
>    at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
> 
>   Questa eccezione è stata generata in origine nello stack di chiamate seguente:
>     [Codice esterno]
>     WebTodoList.Api.Services.TodoControllerServices.GetTodoListItems(bool) in TodoControllerServices.cs
>     WebTodoList.Api.Controllers.TodoController.Get(bool) in TodoController.cs
>     [Codice esterno]

**Comment by albx** [comment]
Ciao,

il database va creato tramite Migrations di EntityFrameworkCore.
Il problema dovrebbe risolversi lanciando lo script powershell initdb.ps1 che trovi nella root del progetto (o copiando il contenuto dello script in un terminal nel caso non fossi su un sistema che supporta gli script powershell).

Resta il fatto che effettivamente è una mancanza di documentazione della cosa. Aggiorno il Readme nei prossimi giorni.

Fammi sapere se risolvi.

**Comment by danixbsc** [comment]
Ti ringrazio, problema risolto. In caso volessi specificarlo nel Readme ( lo dico visto che l'ho fatto anche io) prima dell'esecuzione dello script va installato il tool, io ho utilizzato il comando `dotnet tool install --global dotnet-ef ` trovato su google Non so se esistono altri metodi.

**Comment by albx** [comment]
Yep, su vero. Se ti va e hai tempo integra pure il readme con queste info e fai pure PR :)
